# Generated by Django 6.0.3 on 2026-03-20 10:28

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='writing_assistant.document')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['document'], name='chunk_document_idx')],
            },
        ),
    ]
